# Add GOBIN to path for Archimede
GOBIN=/usr/local/go/bin
PATH=$GOBIN:$PATH

# howdoi alias for when that's figured out
hdi(){
 	/home/wizard/env/bin/howdoi $* -c -n 5
}

# WTTR RULES
# If you source this file, it will set WTTR_PARAMS as well as show weather.

# WTTR_PARAMS is space-separated URL parameters, many of which are single characters that can be
# lumped together. For example, "F q m" behaves the same as "Fqm".
if [[ -z "$WTTR_PARAMS" ]]; then
  # Form localized URL parameters for curl
  if [[ -t 1 ]] && [[ "$(tput cols)" -lt 125 ]]; then
      WTTR_PARAMS+='n'
  fi 2> /dev/null
  for _token in $( locale LC_MEASUREMENT ); do
    case $_token in
      1) WTTR_PARAMS+='m' ;;
      2) WTTR_PARAMS+='u' ;;
    esac
  done 2> /dev/null
  unset _token
  export WTTR_PARAMS
fi

wttr() {
  local location="${1// /+}"
  test "$#" -gt 0 && shift
  local args=()
  for p in $WTTR_PARAMS "$@"; do
    args+=("--data-urlencode" "$p")
  done
  curl -fGsS -H "Accept-Language: ${LANG%_*}" "${args[@]}" --compressed "wttr.in/${location}"
}

# fff alias
f(){
	fff "$@"
	cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
}

# exa aliases
alias ls='exa --icons=auto --colour=always --group-directories-first -bhH'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -al'
alias llt='ls -alT'


# keyd default config path
KEYD_DEFAULTS=/etc/keyd/default.conf

ssh-copy-win-id() {
    KEY_LOCATION=$1
    DESTINATION=$2
    SSH_PORT=$3
    ADMIN=$4

    # Validate Key File exists
    if [ ! -f $KEY_LOCATION ]; then
        echo "$KEY_LOCATION"
        return 1
    fi

    # Validate that destination isn't empty
    if [ -z $DESTINATION ]; then
        echo "Must provide a destination <user>@<ip>"
        return 1
    fi

    # Use default SSH port if needed
    if [ -z $SSH_PORT ]; then
        echo "No SSH_PORT provided, using 22"
        SSH_PORT="22"
    fi
    
    authorized_key=$(cat $KEY_LOCATION)
    if [ -z $authorized_key ]; then
        echo "Empty authorized key: $authorized_key"
        return 1
    fi

    # For a standard user:
    ssh_command="powershell New-Item -Force -ItemType Directory -Path \$env:USERPROFILE\\.\\ssh; Add-Content -Force -Path \$env:USERPROFILE\\.\\ssh\\authorized_keys -Value \'$authorized_key\'"

    if [ $ADMIN -eq 1 ]; then
        # Generate the PowerShell command to run remotely that copies the public key file generated previously on your client to the authorized_keys file on your server
        ssh_command="powershell Add-Content -Force -Path \$env:ProgramData\ssh\administrators_authorized_keys -Value '$authorized_key';icacls.exe \"\$env:ProgramData\ssh\administrators_authorized_keys\" /inheritance:r /grant \"Administrators:F\" /grant \"SYSTEM:F\""
    fi

# Connect to your server and run the PowerShell command by using the $remotePowerShell variable.
    ssh -p $SSH_PORT $DESTINATION $ssh_command
}

function y() {
    local sock="/tmp/yazi-mpv.sock"
    if ! pgrep -f "input-ipc-server=$sock" > /dev/null; then
        rm -rf "$sock"
        mpv --idle --no-video --no-terminal --volume=70 --input-ipc-server="$sock" &
        # Run with debug?
        # mpv --idle --no-video --no-terminal --volume=70 \
        # --input-ipc-server="$sock" \
        # --msg-level=ipc=debug --log-file=/tmp/mpv.log &
        disown
    fi

    # Stop the last clip from playing
    trap 'echo "{\"command\": [\"stop\"]}" | socat - "'"$sock"'" 2>/dev/null' EXIT

	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
	command rm -f -- "$tmp"
}

assbrow(){
    y /srv/assets $(pwd)/$1
}

export PROJECTS="~/Projects"

yp(){
    y $PROJECTS
}
